name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this if your default branch is not `main`

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0 # Update if a newer Ruby version is required
        bundler-cache: true

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Step 4: Build the site
    - name: Build site
      run: bundle exec jekyll build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

